=== DAW-25-27-TIERNO/XML/xsd/poo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://tierno.es/poo"
    elementFormDefault="qualified">
    <xs:element name="classes">
        <xs:complexType>
            <xs:sequence>
                <!-- Aquí definición del elemento final -->
                <xs:element name="final">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- definition -->
                            <xs:element name="definition" type="xs:string" />
                            <!-- declaration -->
                            <xs:element name="declaration" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string"> <!-- este xs:string se
                                            refiere al
                                        contenido del elemento -->
                                            <xs:attribute name="language" type="xs:string" /> <!--
                                            este
                                        xs:string se refiere al contenido del atributo-->
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
                <!-- Aquí definición del elemento abstract -->
                <xs:element name="abstract">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- definition -->
                            <xs:element name="definition" type="xs:string" />
                            <!-- declaration -->
                            <xs:element name="declaration" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string"> <!-- este xs:string se
                                            refiere al
                                contenido del elemento -->
                                            <xs:attribute name="language" type="xs:string" /> <!--
                                            este xs:string
                                se refiere al contenido del atributo-->
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DAW-25-27-TIERNO/XML/xsd/poo.xml
<classes
    xmlns="http://tierno.es/poo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tierno.es/poo poo.xsd">
    <final>
        <definition>Clase final que no admite herencia</definition>
        <declaration language="java">public final class [name] { }</declaration>
        <declaration language="php">final class [name] { }</declaration>
    </final>
    
    <abstract>
        <definition>Clase de la que no se pueden instanciar objetos</definition>
        <declaration language="java">public abstract class [name]</declaration>
        <declaration language="php">abstract class [name]</declaration>
    </abstract>
</classes>
